# Generated by Django 5.2.17 on 2026-09-26 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('Maquillaje', 'Maquillaje'), ('Cuidado facial', 'Cuidado facial'), ('Cuidado capilar', 'Cuidado capilar'), ('Cuidado corporal', 'Cuidado corporal'), ('Perfumería', 'Perfumería'), ('Uñas', 'Uñas'), ('Accesorios de belleza', 'Accesorios de belleza')], max_length=30, verbose_name='Categoría')),
                ('marca', models.CharField(blank=True, max_length=80, verbose_name='Marca')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('cantidad_existente', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad existente')),
                ('stock_minimo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
